//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::articles::Entity as Articles;
pub use super::comments::Entity as Comments;
pub use super::movies::Entity as Movies;
pub use super::users::Entity as Users;
